networks:
    anony-mate-frontend-network:
        driver: bridge

services:
    nginx:
        extends:
            file: ./docker/services.compose.yml
            service: nginx
        depends_on:
            - anony-mate-frontend-frontend
        networks:
            - anony-mate-frontend-network

    llm:
        extends:
            file: ./docker/services.compose.yml
            service: llm
        networks:
            - anony-mate-frontend-network

    anony-mate-frontend-backend:
        extends:
            file: ./docker/services.compose.yml
            service: anony-mate-frontend-backend
        networks:
            - anony-mate-frontend-network

    anony-mate-frontend-frontend:
        extends:
            file: ./docker/services.compose.yml
            service: anony-mate-frontend-frontend
        networks:
            - anony-mate-frontend-network
